<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.1" />
      <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.1" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\uploads\chat\7\2604f0ea08dd4bc3995206aa70bf6444.docx" />
      <_ContentIncludedByDefault Remove="wwwroot\uploads\chat\7\c73f5f241577450e992120c0b58c413c.docx" />
      <_ContentIncludedByDefault Remove="wwwroot\uploads\chat\11\6724708840e54222a8037eecedf84d2d.png" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\uploads\chat\" />
    </ItemGroup>

</Project>
